### PR TITLE
Address Snyk issues

### PR DESCRIPTION
**Pull request by juniortaeza**
### Desired Outcome

This pull request addresses the Snyk vulnerabilities outlined in this repository.

#### Changelog

- [X] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes, or
- [X] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]
- [X] This PR does not require updating any documentation

#### Behavior

- [ ] This PR changes product behavior and has been reviewed by a PO, or
- [X] These changes are part of a larger initiative that will be reviewed later, or
- [ ] No behavior was changed with this PR

#### Security

- [ ] Security architect has reviewed the changes in this PR,
- [X] These changes are part of a larger initiative with a separate security review, or
- [ ] There are no security aspects to these changes

### CODE REVIEW

**Comment by szh** [comment]
Please make sure to test the changes following the instructions in CONTRIBUTING.md

**Comment by juniortaeza** [comment]
Testing 'secure-ci-cd-pipelines' yields successful results for this Python upgrade, but 'secure-ansible-automation' and 'secure-kubernetes-secrets' fail with the following log:

`[ERROR] Error verifying check: Expected challenge status 'completed', but got 'started'`

The same error message is showing when running the tests on the main branch. Is this valid to approve the Python upgrade? @szh

**Review by szh — APPROVED** [review]
Given the way the tracks use these files (by checking them out from git at runtime), and given the fact that this is simply a minor Python upgrade for a super simple Python script, I say we merge this and then just ensure the tracks still work afterwards.

**Comment by szh** [comment]
@juniortaeza I should not that you will *not* need to push the track up to Instruqt for this update, since the changes aren't in the `tracks` directory but are actually pulled down at runtime from GitHub.

**Comment by juniortaeza** [comment]
Sounds good! @szh Thank you for letting me know :)

**Pull request merged**
