### PR TITLE
Update CI/CD and Secretless tracks for Conjur CLI v8.0

### PR DESCRIPTION
**Pull request by szh**
### Desired Outcome

Update https://play.instruqt.com/cyberark/tracks/secure-ci-cd-pipelines-v2 and https://play.instruqt.com/cyberark/tracks/secure-kubernetes-secrets-v2 to use Conjur CLI v8.0.

### Connected Issue/Story

CyberArk internal issue ID: ONYX-32707

### CODE REVIEW

**Review by john-odonnell — COMMENTED** [review]
Step 9 in the `secure-kubernetes-secrets` track is using a script with outdated CLI calls to initialize the CA. Looks like it's being pulled in [during setup](https://github.com/cyberark/conjur-instruqt/blob/main/tracks/conjur.org/secure-kubernetes-secrets/track_scripts/setup-server#L41) from [this repo](https://github.com/scarolan/instruqt/blob/main/env/conjur-k8s/conjur/initialize_ca.sh).

This is probably what's causing Secretless to field 401 errors later in the track:
```
Info: Conjur provider is authenticating ...
INFO: authenticator.go:84: CAKC040 Authenticating as user 'host/conjur/authn-k8s/dev/apps/service-account-based-app'
ERROR: authenticator.go:185: CAKC029 Received invalid response to certificate signing request. Reason: status code 401, 
ERROR: authenticator.go:271: CAKC015 Login failed
```

**Comment by szh** [comment]
Oh good catch! I updated the setup script

**Comment by john-odonnell** [comment]
Been waiting to re-review until I can run through the track again, but it's still under maintenance.

Screenshot 2023-02-24 at 9 08 03 AM

**Review by john-odonnell — APPROVED** [review]
LGTM!

**Pull request merged**
